### PR TITLE
Try to add tmux-support to starter

### PR DESCRIPTION
**Pull request by ObiWahn**
This branch tries to add tmux support to the starter. This will allow for running instances with attached consoles.

### CODE REVIEW

**Comment by ObiWahn** [comment]
How do you check if some instance has been started?

**Comment by ewoutp** [comment]
Why do we need this?

**Comment by ObiWahn** [comment]
We need this we are not able to access arangod with --console as the starter works now.

**Comment by ObiWahn** [comment]
I get the following output that shows how the single server is failing:

`2018/05/07 13:45:43 Starting single on port 8529
2018/05/07 13:45:43 running command: [/usr/bin/tmux new-session -s arangod8529 ./build/bin/arangod -c /home/oberon/arangodb1/single8529/arangod.conf --database.directory /home/oberon/arangodb1/single8529/data --javascript.startup-directory /home/oberon/arangodb1/js --javascript.app-path /home/oberon/arangodb1/single8529/apps --log.file /home/oberon/arangodb1/single8529/arangod.log --log.force-direct false --foxx.queues true --server.statistics true --console]
2018/05/07 13:45:43 single has terminated quickly, in 2.033628ms (recent failures: 100)
2018/05/07 13:45:43 ## Start of single log
	2018-05-07T11:39:15Z [11566] INFO ArangoDB has been shut down
	2018-05-07T11:44:49Z [14500] INFO {authentication} Jwt secret not specified, generating...
	2018-05-07T11:44:49Z [14500] INFO ArangoDB 3.4.devel [linux] 64bit maintainer mode, using build heads/feature/RepSert-0-g3fe2861e16-dirty, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0h  27 Mar 2018
	2018-05-07T11:44:49Z [14500] INFO detected operating system: Linux version 4.16.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 7.3.0 (Debian 7.3.0-17)) #1 SMP Debian 4.16.5-1 (2018-04-29)
	2018-05-07T11:44:49Z [14500] WARNING {memory} environment variable GLIBCXX_FORCE_NEW' is not set. it is recommended to set it to some value to avoid unnecessary memory pooling in glibc++
`

When I copy the command to the command-line i am able to start tmux. What can I do to find out what is going wrong here?

**Pull request closed without merging**
