### PR TITLE
Split readme in readme & manual part

### PR DESCRIPTION
**Pull request by ewoutp**
Splitting README in README & manual part.

### CODE REVIEW

**Comment by ewoutp** [comment]
@sleto-id @neunhoef  Please review.

This is first proposal, structure, folders & filenames are all open to suggestions.

**Comment by sleto-it** [comment]
@ewoutp Hi and many thanks!!

I suggest:

1. Create directory GettingStarted/Starter/ and move in it the file usage.md
2. Rename usage.md in README.md 

above points are needed to integrate the file in the Getting Starter Doc

3. Create directory Programs/Starter and move in it the files options.md and security.md

4. Add in Programs/Starter a new file README.md, which content like the following:

```
# ArangoDB Starter

This chapter documents the _ArangoDB Starter_.

The _ArangoDB Starter_ is a tool that can help you deploy ArangoDB in an easy way (either in single-instance, active/passive or Cluster mode).

For a Tutorial, please refer to [this](../GettingStarted/Starter/README.md) section.
```

Thanks a lot for working on this! and I think after these changes and merge I can quickly create integration into our official manual :))

**Comment by ewoutp** [comment]
@sleto-it changed as you suggested. Please review this PR once more and when approved, I'll merge it

**Comment by sleto-it** [comment]
@ewoutp - okay for me - please let's merge this and I will work to merge https://github.com/arangodb/arangodb/pull/4549

**Pull request merged**
